### ISSUE TITLE
How to deploy on Zeit

### ISSUE THREAD

**Issue by brewmanandi** [GenaBitu/NIMP#2]
I tried to deploy nimp on Zeit but keep getting a 404 response on POST requests for all api routes (i.e. /api/login)

![image](https://user-images.githubusercontent.com/2788521/72432713-fea46f00-3797-11ea-8d23-20ea40e79c6d.png)

**Comment by marekdedic** [comment]
Hi,
what? I have no idea what you're talking about...

Marek

**Comment by marekdedic** [comment]
Hi, if you mean https://zeit.co/, then I think you've got something mismatched... This is not a web application, this is a desktop app.

Closing for now, if you think I've misunderstood, do tell me please.

**Comment by brewmanandi** [comment]
Oh... wrong nimp repo...

**Comment by marekdedic** [comment]
No worries ;)
